title: Stanny Nuytkens
email: stanny@nuytkens.com
description: > # this means to ignore newlines until "baseurl:"
  Me, writing about stuff!
baseurl: ""
url: http://stanny.nuytkens.com

twitter_username: stannnuy
github_username:  stannynuytkens
stackoverflow_userid: 1431545
steam_id: grmbl

# Server Config options
livereload: true

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

timezone: Europe/Brussels

permalink: /talks-about/:title/on/:year:month

incremental: true

sass:
    style: compressed
    sass_dir: _sass
