baseURL = "https://stanny.nuytkens.com"
languageCode = "en-us"
title = "Stanny Nuytkens"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"
enableEmoji = true

disqusShortname = "stanny-nuytkens-com"
googleAnalytics = "UA-111646602-1"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params]
addThis = "ra-5a465279ff6a1f31"

[params.info]
description = "developer : internaut : father"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
# customJS = ["js/custom.js"]
customJS = []
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Stanny Nuytkens"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = ""
email = "stanny@nuytkens.com"
facebook = ""
github = "stannynuytkens"
instagram = ""
linkedin = ""
twitter = "stannnuy"
telegram = ""

[params.social.config]
platforms = ["github","twitter","email"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
mood = "moods"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Home"
identifier = "home"
url = "/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1